### ISSUE TITLE
Unwanted renaming

### ISSUE THREAD

**Issue by vajexal** [amphp/php-cs-fixer-config#5]
`psr_autoloading` rule doesn't support few code sources (`src` and `tests` for example), which leads to files renaming. For example if we run

```bash
vendor/bin/php-cs-fixer fix
```
on [github.com/amphp/amp](https://github.com/amphp/amp), test files will be renamed

```diff
-class FilterTest extends BaseTest
+class t_FilterTest extends BaseTest
```

Could this rule be removed?

**Comment by kelunik** [comment]
I noticed that as well, but haven't found out what caused that change. I'd like to keep the rule, as it also checks the correct casing of files, but I'd like to disable it for all directories not being `src` / `lib`. That was the intention behind https://github.com/amphp/php-cs-fixer-config/commit/e504817c8ea806b4575b1fec88f9e9c2de635c63 and https://github.com/amphp/php-cs-fixer-config/commit/09a43ad9d544b9a51a4e8cd3ebc30c0a77b0f8b5, but it didn't work like I expected. Any idea how to do that?

**Comment by vajexal** [comment]
[here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/6ff9ab5785752f6d186daf28edcefe28a518f1b8/src/Fixer/Basic/PsrAutoloadingFixer.php#L220) is the reason I think. For example `$maxNamespace` for [FilterTest.php](https://github.com/amphp/amp/blob/dbb3c28ece24b36efa91be205f6f0b015bddc27c/test/FilterTest.php) will be `t` because file path (`test/FilterTest.php`) minus root path (`lib`) is `t/FilterTest.php` and without filename it's `t`.

There's no way to configure phpcs fixer to ignore some rules for specific path as I know. Other solutions relate to [github.com/FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by kelunik** [comment]
I've opened https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5421.

**Comment by kelunik** [comment]
I've temporarily disabled the rule, but will keep the issue open until it's fixed.

**Comment by kelunik** [comment]
The fix has been merged, so I'll close this one as well. :smile:
