### ISSUE TITLE
Upgrade to php-cs-fixer: ^3 ?

### ISSUE THREAD

**Issue by Pato05** [amphp/php-cs-fixer-config#6]
Hello, I have been using this configuration for quite a while now, and I really enjoy it, but it still runs on php-cs-fixer 2.x

Will this be upgraded to 3.x?

**Comment by kelunik** [comment]
Yes, but we need some other branch I guess, as we use  dev-master everywhere.

**Comment by kelunik** [comment]
There's a `v2` branch now.
